### ISSUE TITLE
Code is not compatible with Three.js r72+

### ISSUE THREAD

**Issue by yokotsumo** [tomtung/chameleon.js#9]
After THREE.js r72, painting is not rendered in real time and all painted faces are transparent when mouse is down. I have hard times finding why. Do you have any clues about the possible causes?

**Comment by tomtung** [comment]
Unfortunately, I haven't been following Three.js for years, and its API might have changed drastically in the meantime. At this point, this repository is better thought of as a standalone web app rather than a reusable JS library that works with Three.js.
